osx_image: xcode10.1
language: swift
xcode_sdk: iphonesimulator10.1
script:
- set -o pipefail && xcodebuild test -project AstrologyCalc.xcodeproj -scheme AstrologyCalcTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7' ONLY_ACTIVE_ARCH=NO | xcpretty -c --test --color
notifications:
  slack: eskaria:RRTsJOW40z95SajyTLBy7lxy
