language: swift
os: osx
osx_image: xcode10.1
xcode_project: Astrology Calculator.xcodeproj # path to your xcodeproj folder
xcode_scheme: Astrology CalculatorTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone XS Max
notifications:
email: true
